---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: p000-pslq
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/psql_pv0001/

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-volume
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: psql-container
          image: postgres:alpine
          ports:
            - containerPort: 8080
          volumeMounts:
             - name: data-store
               mountPath: /var/lib/postgresql
      volumes:
        - name: data-store
          PersistentVolumeClaim:
            claimName: postgresql-volume
